// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.30.2
// source: appointment/v1/appointment.proto

package appointmentv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AppointmentStatus int32

const (
	AppointmentStatus_APPOINTMENT_STATUS_UNSPECIFIED AppointmentStatus = 0
	AppointmentStatus_APPOINTMENT_STATUS_NEW         AppointmentStatus = 1
	AppointmentStatus_APPOINTMENT_STATUS_IN_PROGRESS AppointmentStatus = 2
	AppointmentStatus_APPOINTMENT_STATUS_DONE        AppointmentStatus = 3
)

// Enum value maps for AppointmentStatus.
var (
	AppointmentStatus_name = map[int32]string{
		0: "APPOINTMENT_STATUS_UNSPECIFIED",
		1: "APPOINTMENT_STATUS_NEW",
		2: "APPOINTMENT_STATUS_IN_PROGRESS",
		3: "APPOINTMENT_STATUS_DONE",
	}
	AppointmentStatus_value = map[string]int32{
		"APPOINTMENT_STATUS_UNSPECIFIED": 0,
		"APPOINTMENT_STATUS_NEW":         1,
		"APPOINTMENT_STATUS_IN_PROGRESS": 2,
		"APPOINTMENT_STATUS_DONE":        3,
	}
)

func (x AppointmentStatus) Enum() *AppointmentStatus {
	p := new(AppointmentStatus)
	*p = x
	return p
}

func (x AppointmentStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AppointmentStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_appointment_v1_appointment_proto_enumTypes[0].Descriptor()
}

func (AppointmentStatus) Type() protoreflect.EnumType {
	return &file_appointment_v1_appointment_proto_enumTypes[0]
}

func (x AppointmentStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AppointmentStatus.Descriptor instead.
func (AppointmentStatus) EnumDescriptor() ([]byte, []int) {
	return file_appointment_v1_appointment_proto_rawDescGZIP(), []int{0}
}

type Appointment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	DoctorId      string                 `protobuf:"bytes,4,opt,name=doctor_id,json=doctorId,proto3" json:"doctor_id,omitempty"`
	Status        AppointmentStatus      `protobuf:"varint,5,opt,name=status,proto3,enum=appointment.v1.AppointmentStatus" json:"status,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Appointment) Reset() {
	*x = Appointment{}
	mi := &file_appointment_v1_appointment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Appointment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Appointment) ProtoMessage() {}

func (x *Appointment) ProtoReflect() protoreflect.Message {
	mi := &file_appointment_v1_appointment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Appointment.ProtoReflect.Descriptor instead.
func (*Appointment) Descriptor() ([]byte, []int) {
	return file_appointment_v1_appointment_proto_rawDescGZIP(), []int{0}
}

func (x *Appointment) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Appointment) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Appointment) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Appointment) GetDoctorId() string {
	if x != nil {
		return x.DoctorId
	}
	return ""
}

func (x *Appointment) GetStatus() AppointmentStatus {
	if x != nil {
		return x.Status
	}
	return AppointmentStatus_APPOINTMENT_STATUS_UNSPECIFIED
}

func (x *Appointment) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Appointment) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type GetAppointmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAppointmentRequest) Reset() {
	*x = GetAppointmentRequest{}
	mi := &file_appointment_v1_appointment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAppointmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAppointmentRequest) ProtoMessage() {}

func (x *GetAppointmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_appointment_v1_appointment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAppointmentRequest.ProtoReflect.Descriptor instead.
func (*GetAppointmentRequest) Descriptor() ([]byte, []int) {
	return file_appointment_v1_appointment_proto_rawDescGZIP(), []int{1}
}

func (x *GetAppointmentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetAppointmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Appointment   *Appointment           `protobuf:"bytes,1,opt,name=appointment,proto3" json:"appointment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAppointmentResponse) Reset() {
	*x = GetAppointmentResponse{}
	mi := &file_appointment_v1_appointment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAppointmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAppointmentResponse) ProtoMessage() {}

func (x *GetAppointmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_appointment_v1_appointment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAppointmentResponse.ProtoReflect.Descriptor instead.
func (*GetAppointmentResponse) Descriptor() ([]byte, []int) {
	return file_appointment_v1_appointment_proto_rawDescGZIP(), []int{2}
}

func (x *GetAppointmentResponse) GetAppointment() *Appointment {
	if x != nil {
		return x.Appointment
	}
	return nil
}

type ListAppointmentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAppointmentsRequest) Reset() {
	*x = ListAppointmentsRequest{}
	mi := &file_appointment_v1_appointment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAppointmentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAppointmentsRequest) ProtoMessage() {}

func (x *ListAppointmentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_appointment_v1_appointment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAppointmentsRequest.ProtoReflect.Descriptor instead.
func (*ListAppointmentsRequest) Descriptor() ([]byte, []int) {
	return file_appointment_v1_appointment_proto_rawDescGZIP(), []int{3}
}

type ListAppointmentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Appointments  []*Appointment         `protobuf:"bytes,1,rep,name=appointments,proto3" json:"appointments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAppointmentsResponse) Reset() {
	*x = ListAppointmentsResponse{}
	mi := &file_appointment_v1_appointment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAppointmentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAppointmentsResponse) ProtoMessage() {}

func (x *ListAppointmentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_appointment_v1_appointment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAppointmentsResponse.ProtoReflect.Descriptor instead.
func (*ListAppointmentsResponse) Descriptor() ([]byte, []int) {
	return file_appointment_v1_appointment_proto_rawDescGZIP(), []int{4}
}

func (x *ListAppointmentsResponse) GetAppointments() []*Appointment {
	if x != nil {
		return x.Appointments
	}
	return nil
}

type CreateAppointmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	DoctorId      string                 `protobuf:"bytes,3,opt,name=doctor_id,json=doctorId,proto3" json:"doctor_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAppointmentRequest) Reset() {
	*x = CreateAppointmentRequest{}
	mi := &file_appointment_v1_appointment_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAppointmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAppointmentRequest) ProtoMessage() {}

func (x *CreateAppointmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_appointment_v1_appointment_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAppointmentRequest.ProtoReflect.Descriptor instead.
func (*CreateAppointmentRequest) Descriptor() ([]byte, []int) {
	return file_appointment_v1_appointment_proto_rawDescGZIP(), []int{5}
}

func (x *CreateAppointmentRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateAppointmentRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateAppointmentRequest) GetDoctorId() string {
	if x != nil {
		return x.DoctorId
	}
	return ""
}

type CreateAppointmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Appointment   *Appointment           `protobuf:"bytes,1,opt,name=appointment,proto3" json:"appointment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAppointmentResponse) Reset() {
	*x = CreateAppointmentResponse{}
	mi := &file_appointment_v1_appointment_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAppointmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAppointmentResponse) ProtoMessage() {}

func (x *CreateAppointmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_appointment_v1_appointment_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAppointmentResponse.ProtoReflect.Descriptor instead.
func (*CreateAppointmentResponse) Descriptor() ([]byte, []int) {
	return file_appointment_v1_appointment_proto_rawDescGZIP(), []int{6}
}

func (x *CreateAppointmentResponse) GetAppointment() *Appointment {
	if x != nil {
		return x.Appointment
	}
	return nil
}

type UpdateAppointmentStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        AppointmentStatus      `protobuf:"varint,2,opt,name=status,proto3,enum=appointment.v1.AppointmentStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAppointmentStatusRequest) Reset() {
	*x = UpdateAppointmentStatusRequest{}
	mi := &file_appointment_v1_appointment_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAppointmentStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAppointmentStatusRequest) ProtoMessage() {}

func (x *UpdateAppointmentStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_appointment_v1_appointment_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAppointmentStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateAppointmentStatusRequest) Descriptor() ([]byte, []int) {
	return file_appointment_v1_appointment_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateAppointmentStatusRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateAppointmentStatusRequest) GetStatus() AppointmentStatus {
	if x != nil {
		return x.Status
	}
	return AppointmentStatus_APPOINTMENT_STATUS_UNSPECIFIED
}

type UpdateAppointmentStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Appointment   *Appointment           `protobuf:"bytes,1,opt,name=appointment,proto3" json:"appointment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAppointmentStatusResponse) Reset() {
	*x = UpdateAppointmentStatusResponse{}
	mi := &file_appointment_v1_appointment_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAppointmentStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAppointmentStatusResponse) ProtoMessage() {}

func (x *UpdateAppointmentStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_appointment_v1_appointment_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAppointmentStatusResponse.ProtoReflect.Descriptor instead.
func (*UpdateAppointmentStatusResponse) Descriptor() ([]byte, []int) {
	return file_appointment_v1_appointment_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateAppointmentStatusResponse) GetAppointment() *Appointment {
	if x != nil {
		return x.Appointment
	}
	return nil
}

var File_appointment_v1_appointment_proto protoreflect.FileDescriptor

const file_appointment_v1_appointment_proto_rawDesc = "" +
	"\n" +
	" appointment/v1/appointment.proto\x12\x0eappointment.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa3\x02\n" +
	"\vAppointment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1b\n" +
	"\tdoctor_id\x18\x04 \x01(\tR\bdoctorId\x129\n" +
	"\x06status\x18\x05 \x01(\x0e2!.appointment.v1.AppointmentStatusR\x06status\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"'\n" +
	"\x15GetAppointmentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"W\n" +
	"\x16GetAppointmentResponse\x12=\n" +
	"\vappointment\x18\x01 \x01(\v2\x1b.appointment.v1.AppointmentR\vappointment\"\x19\n" +
	"\x17ListAppointmentsRequest\"[\n" +
	"\x18ListAppointmentsResponse\x12?\n" +
	"\fappointments\x18\x01 \x03(\v2\x1b.appointment.v1.AppointmentR\fappointments\"o\n" +
	"\x18CreateAppointmentRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1b\n" +
	"\tdoctor_id\x18\x03 \x01(\tR\bdoctorId\"Z\n" +
	"\x19CreateAppointmentResponse\x12=\n" +
	"\vappointment\x18\x01 \x01(\v2\x1b.appointment.v1.AppointmentR\vappointment\"k\n" +
	"\x1eUpdateAppointmentStatusRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x129\n" +
	"\x06status\x18\x02 \x01(\x0e2!.appointment.v1.AppointmentStatusR\x06status\"`\n" +
	"\x1fUpdateAppointmentStatusResponse\x12=\n" +
	"\vappointment\x18\x01 \x01(\v2\x1b.appointment.v1.AppointmentR\vappointment*\x94\x01\n" +
	"\x11AppointmentStatus\x12\"\n" +
	"\x1eAPPOINTMENT_STATUS_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16APPOINTMENT_STATUS_NEW\x10\x01\x12\"\n" +
	"\x1eAPPOINTMENT_STATUS_IN_PROGRESS\x10\x02\x12\x1b\n" +
	"\x17APPOINTMENT_STATUS_DONE\x10\x032\xc2\x03\n" +
	"\x12AppointmentService\x12h\n" +
	"\x11CreateAppointment\x12(.appointment.v1.CreateAppointmentRequest\x1a).appointment.v1.CreateAppointmentResponse\x12_\n" +
	"\x0eGetAppointment\x12%.appointment.v1.GetAppointmentRequest\x1a&.appointment.v1.GetAppointmentResponse\x12e\n" +
	"\x10ListAppointments\x12'.appointment.v1.ListAppointmentsRequest\x1a(.appointment.v1.ListAppointmentsResponse\x12z\n" +
	"\x17UpdateAppointmentStatus\x12..appointment.v1.UpdateAppointmentStatusRequest\x1a/.appointment.v1.UpdateAppointmentStatusResponseBYZWgithub.com/emiameaningpressenceinblood/advanced2-protos-go/appointment/v1;appointmentv1b\x06proto3"

var (
	file_appointment_v1_appointment_proto_rawDescOnce sync.Once
	file_appointment_v1_appointment_proto_rawDescData []byte
)

func file_appointment_v1_appointment_proto_rawDescGZIP() []byte {
	file_appointment_v1_appointment_proto_rawDescOnce.Do(func() {
		file_appointment_v1_appointment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_appointment_v1_appointment_proto_rawDesc), len(file_appointment_v1_appointment_proto_rawDesc)))
	})
	return file_appointment_v1_appointment_proto_rawDescData
}

var file_appointment_v1_appointment_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_appointment_v1_appointment_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_appointment_v1_appointment_proto_goTypes = []any{
	(AppointmentStatus)(0),                  // 0: appointment.v1.AppointmentStatus
	(*Appointment)(nil),                     // 1: appointment.v1.Appointment
	(*GetAppointmentRequest)(nil),           // 2: appointment.v1.GetAppointmentRequest
	(*GetAppointmentResponse)(nil),          // 3: appointment.v1.GetAppointmentResponse
	(*ListAppointmentsRequest)(nil),         // 4: appointment.v1.ListAppointmentsRequest
	(*ListAppointmentsResponse)(nil),        // 5: appointment.v1.ListAppointmentsResponse
	(*CreateAppointmentRequest)(nil),        // 6: appointment.v1.CreateAppointmentRequest
	(*CreateAppointmentResponse)(nil),       // 7: appointment.v1.CreateAppointmentResponse
	(*UpdateAppointmentStatusRequest)(nil),  // 8: appointment.v1.UpdateAppointmentStatusRequest
	(*UpdateAppointmentStatusResponse)(nil), // 9: appointment.v1.UpdateAppointmentStatusResponse
	(*timestamppb.Timestamp)(nil),           // 10: google.protobuf.Timestamp
}
var file_appointment_v1_appointment_proto_depIdxs = []int32{
	0,  // 0: appointment.v1.Appointment.status:type_name -> appointment.v1.AppointmentStatus
	10, // 1: appointment.v1.Appointment.created_at:type_name -> google.protobuf.Timestamp
	10, // 2: appointment.v1.Appointment.updated_at:type_name -> google.protobuf.Timestamp
	1,  // 3: appointment.v1.GetAppointmentResponse.appointment:type_name -> appointment.v1.Appointment
	1,  // 4: appointment.v1.ListAppointmentsResponse.appointments:type_name -> appointment.v1.Appointment
	1,  // 5: appointment.v1.CreateAppointmentResponse.appointment:type_name -> appointment.v1.Appointment
	0,  // 6: appointment.v1.UpdateAppointmentStatusRequest.status:type_name -> appointment.v1.AppointmentStatus
	1,  // 7: appointment.v1.UpdateAppointmentStatusResponse.appointment:type_name -> appointment.v1.Appointment
	6,  // 8: appointment.v1.AppointmentService.CreateAppointment:input_type -> appointment.v1.CreateAppointmentRequest
	2,  // 9: appointment.v1.AppointmentService.GetAppointment:input_type -> appointment.v1.GetAppointmentRequest
	4,  // 10: appointment.v1.AppointmentService.ListAppointments:input_type -> appointment.v1.ListAppointmentsRequest
	8,  // 11: appointment.v1.AppointmentService.UpdateAppointmentStatus:input_type -> appointment.v1.UpdateAppointmentStatusRequest
	7,  // 12: appointment.v1.AppointmentService.CreateAppointment:output_type -> appointment.v1.CreateAppointmentResponse
	3,  // 13: appointment.v1.AppointmentService.GetAppointment:output_type -> appointment.v1.GetAppointmentResponse
	5,  // 14: appointment.v1.AppointmentService.ListAppointments:output_type -> appointment.v1.ListAppointmentsResponse
	9,  // 15: appointment.v1.AppointmentService.UpdateAppointmentStatus:output_type -> appointment.v1.UpdateAppointmentStatusResponse
	12, // [12:16] is the sub-list for method output_type
	8,  // [8:12] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_appointment_v1_appointment_proto_init() }
func file_appointment_v1_appointment_proto_init() {
	if File_appointment_v1_appointment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_appointment_v1_appointment_proto_rawDesc), len(file_appointment_v1_appointment_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_appointment_v1_appointment_proto_goTypes,
		DependencyIndexes: file_appointment_v1_appointment_proto_depIdxs,
		EnumInfos:         file_appointment_v1_appointment_proto_enumTypes,
		MessageInfos:      file_appointment_v1_appointment_proto_msgTypes,
	}.Build()
	File_appointment_v1_appointment_proto = out.File
	file_appointment_v1_appointment_proto_goTypes = nil
	file_appointment_v1_appointment_proto_depIdxs = nil
}
